### ISSUE TITLE
Transform overlay todo

### ISSUE THREAD

**Issue by Equbuxu** [PixiEditor/PixiEditorPrototype#27]
- [ ] Snap to pixels
- [ ] Drag the whole thing
- [ ] Move to a separate project?
